POST http://localhost:5000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImVtYWlsIjoiYnV5ZXI0QGdtYWlsLmNvbSIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTY2NzIyNzgzMywiZXhwIjoxNjY3NjU5ODMzfQ.hL5G5QUg2Kbsd7C9jD5iUWWf8UdlldVNflN0LQf4wAw"
}